name: e_commercehybrid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^15.1.3
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  fluttertoast: ^8.2.12
  flutter_otp_text_field: ^1.5.1+1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splashscreenlaza.png
    - assets/shoppingbags.png
    - assets/email.webp
    - assets/testprofile.jpg
    - assets/changepassword.webp
    - assets/bucket.png
    - assets/carousel1.png
    - assets/carousel2.jpg
    - assets/carousel3.png
    - assets/carousel4.jpg
    - assets/homeicon.png
    - assets/homeactive.png
    - assets/bookicon.png
    - assets/bookactive.png
    - assets/shoppingicon.png
    - assets/shoppingactive.png
    - assets/hearticon.png
    - assets/heartactive.png
    - assets/noprofile.png
    - assets/filter.png
    
    - assets/promo1.jpg
    - assets/promo2.jpg
    - assets/promo3.jpg
    - assets/promo4.jpg
    - assets/sampleitem.jpeg
    - assets/sampleitem2.jpeg
    - assets/sampleitem3.jpeg
    - assets/sampleitem4.jpg
    - assets/sampleitem5.jpg


    - assets/fonts/RalewayBlack.ttf
    - assets/fonts/RalewayRegular.ttf  # Must include font file in assets

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayBlack.ttf
    - family: RalewayRegular
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf

   
  
      