// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqzUeT3S2LtYC2eyVjovBnAZvrJe1Iyw',
    appId: '1:264928021883:web:73177cb484fa64eec841de',
    messagingSenderId: '264928021883',
    projectId: 'laza-12c28',
    authDomain: 'laza-12c28.firebaseapp.com',
    storageBucket: 'laza-12c28.firebasestorage.app',
    measurementId: 'G-1BT761S0QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UZdVpPXoAzcZFsoyMUpsjLQs-qusyi8',
    appId: '1:264928021883:android:83e00ee6f89c561cc841de',
    messagingSenderId: '264928021883',
    projectId: 'laza-12c28',
    storageBucket: 'laza-12c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-FRPJKELlvVcULrLAZ9xThacz4azZ-k',
    appId: '1:264928021883:ios:4b72dd6d39fbbfa3c841de',
    messagingSenderId: '264928021883',
    projectId: 'laza-12c28',
    storageBucket: 'laza-12c28.firebasestorage.app',
    iosBundleId: 'com.example.eCommercehybrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-FRPJKELlvVcULrLAZ9xThacz4azZ-k',
    appId: '1:264928021883:ios:4b72dd6d39fbbfa3c841de',
    messagingSenderId: '264928021883',
    projectId: 'laza-12c28',
    storageBucket: 'laza-12c28.firebasestorage.app',
    iosBundleId: 'com.example.eCommercehybrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzqzUeT3S2LtYC2eyVjovBnAZvrJe1Iyw',
    appId: '1:264928021883:web:50eefdf12359801ec841de',
    messagingSenderId: '264928021883',
    projectId: 'laza-12c28',
    authDomain: 'laza-12c28.firebaseapp.com',
    storageBucket: 'laza-12c28.firebasestorage.app',
    measurementId: 'G-DHC8QHHFDY',
  );
}
